import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const questions = [
  // =========================
  // COMPUTER SCIENCE (25)
  // =========================
  {
    id: 'q_cs_001',
    degreeId: 'deg_cs_001',
    questionText: 'What is the purpose of an algorithm?',
    optionA: 'Store data',
    optionB: 'Solve a problem step by step',
    optionC: 'Connect networks',
    optionD: 'Compile programs',
    correctAnswer: 'B',
  },
  {
    id: 'q_cs_002',
    degreeId: 'deg_cs_001',
    questionText: 'Which number system do computers use internally?',
    optionA: 'Binary',
    optionB: 'Decimal',
    optionC: 'Hexadecimal',
    optionD: 'Octal',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_003',
    degreeId: 'deg_cs_001',
    questionText: 'Which device performs most calculations in a computer?',
    optionA: 'RAM',
    optionB: 'Hard Disk',
    optionC: 'CPU',
    optionD: 'Monitor',
    correctAnswer: 'C',
  },
  {
    id: 'q_cs_004',
    degreeId: 'deg_cs_001',
    questionText: 'Which programming language is commonly used in AI?',
    optionA: 'Python',
    optionB: 'HTML',
    optionC: 'CSS',
    optionD: 'XML',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_005',
    degreeId: 'deg_cs_001',
    questionText: 'Which data structure follows FIFO order?',
    optionA: 'Stack',
    optionB: 'Tree',
    optionC: 'Queue',
    optionD: 'Graph',
    correctAnswer: 'C',
  },
  {
    id: 'q_cs_006',
    degreeId: 'deg_cs_001',
    questionText: 'Which component manages computer hardware and software resources?',
    optionA: 'Compiler',
    optionB: 'Operating System',
    optionC: 'Database',
    optionD: 'Router',
    correctAnswer: 'B',
  },
  {
    id: 'q_cs_007',
    degreeId: 'deg_cs_001',
    questionText: 'What is debugging?',
    optionA: 'Testing software',
    optionB: 'Fixing code errors',
    optionC: 'Designing interfaces',
    optionD: 'Installing programs',
    correctAnswer: 'B',
  },
  {
    id: 'q_cs_008',
    degreeId: 'deg_cs_001',
    questionText: 'Which tool is commonly used for version control?',
    optionA: 'Git',
    optionB: 'Excel',
    optionC: 'Photoshop',
    optionD: 'PowerPoint',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_009',
    degreeId: 'deg_cs_001',
    questionText: 'What does SQL mainly manage?',
    optionA: 'Graphics',
    optionB: 'Networks',
    optionC: 'Structured data',
    optionD: 'Hardware',
    correctAnswer: 'C',
  },
  {
    id: 'q_cs_010',
    degreeId: 'deg_cs_001',
    questionText: 'Which component temporarily stores active program data?',
    optionA: 'SSD',
    optionB: 'RAM',
    optionC: 'CPU',
    optionD: 'Printer',
    correctAnswer: 'B',
  },
  {
    id: 'q_cs_011',
    degreeId: 'deg_cs_001',
    questionText: 'Which concept allows repeating instructions?',
    optionA: 'Loop',
    optionB: 'Array',
    optionC: 'Variable',
    optionD: 'Class',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_012',
    degreeId: 'deg_cs_001',
    questionText: 'Which network type connects computers within a building?',
    optionA: 'LAN',
    optionB: 'WAN',
    optionC: 'VPN',
    optionD: 'PAN',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_013',
    degreeId: 'deg_cs_001',
    questionText: 'Which field focuses on intelligent computer systems?',
    optionA: 'Cybersecurity',
    optionB: 'Artificial Intelligence',
    optionC: 'Networking',
    optionD: 'Graphics',
    correctAnswer: 'B',
  },
  {
    id: 'q_cs_014',
    degreeId: 'deg_cs_001',
    questionText: 'Which storage device is fastest among these?',
    optionA: 'HDD',
    optionB: 'DVD',
    optionC: 'SSD',
    optionD: 'USB',
    correctAnswer: 'C',
  },
  {
    id: 'q_cs_015',
    degreeId: 'deg_cs_001',
    questionText: 'Which protocol powers websites?',
    optionA: 'FTP',
    optionB: 'SMTP',
    optionC: 'HTTP',
    optionD: 'SSH',
    correctAnswer: 'C',
  },
  {
    id: 'q_cs_016',
    degreeId: 'deg_cs_001',
    questionText: 'Which structure stores key-value pairs efficiently?',
    optionA: 'Hash Table',
    optionB: 'Stack',
    optionC: 'Queue',
    optionD: 'Array',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_017',
    degreeId: 'deg_cs_001',
    questionText: 'Which device connects multiple networks?',
    optionA: 'Router',
    optionB: 'Keyboard',
    optionC: 'Printer',
    optionD: 'Monitor',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_018',
    degreeId: 'deg_cs_001',
    questionText: 'Which concept organizes reusable code blocks?',
    optionA: 'Functions',
    optionB: 'Loops',
    optionC: 'Variables',
    optionD: 'Pointers',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_019',
    degreeId: 'deg_cs_001',
    questionText: 'Which language runs in web browsers?',
    optionA: 'JavaScript',
    optionB: 'Python',
    optionC: 'C++',
    optionD: 'Java',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_020',
    degreeId: 'deg_cs_001',
    questionText: 'Which concept hides complex system details?',
    optionA: 'Encapsulation',
    optionB: 'Encryption',
    optionC: 'Compilation',
    optionD: 'Rendering',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_021',
    degreeId: 'deg_cs_001',
    questionText: 'Which field studies large datasets for patterns?',
    optionA: 'Data Science',
    optionB: 'Cybersecurity',
    optionC: 'Networking',
    optionD: 'Graphics',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_022',
    degreeId: 'deg_cs_001',
    questionText: 'Which system schedules processes in a computer?',
    optionA: 'Operating System',
    optionB: 'Compiler',
    optionC: 'Database',
    optionD: 'Browser',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_023',
    degreeId: 'deg_cs_001',
    questionText: 'Which tool hosts code repositories online?',
    optionA: 'GitHub',
    optionB: 'LinkedIn',
    optionC: 'Dropbox',
    optionD: 'Figma',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_024',
    degreeId: 'deg_cs_001',
    questionText: 'Which concept helps secure data communication?',
    optionA: 'Encryption',
    optionB: 'Debugging',
    optionC: 'Rendering',
    optionD: 'Parsing',
    correctAnswer: 'A',
  },
  {
    id: 'q_cs_025',
    degreeId: 'deg_cs_001',
    questionText: 'Which discipline studies algorithms and computation?',
    optionA: 'Computer Science',
    optionB: 'Graphic Design',
    optionC: 'Business Analytics',
    optionD: 'Mechanical Engineering',
    correctAnswer: 'A',
  },

  // =========================
  // SOFTWARE ENGINEERING (25)
  // =========================
  {
    id: 'q_se_001',
    degreeId: 'deg_se_001',
    questionText: 'What is the goal of software engineering?',
    optionA: 'Build reliable software systems',
    optionB: 'Repair hardware',
    optionC: 'Design circuits',
    optionD: 'Manage networks',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_002',
    degreeId: 'deg_se_001',
    questionText: 'What does SDLC stand for?',
    optionA: 'Software Development Life Cycle',
    optionB: 'System Data Logic Code',
    optionC: 'Software Design Level Control',
    optionD: 'System Deployment Language Code',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_003',
    degreeId: 'deg_se_001',
    questionText: 'Which phase gathers user needs?',
    optionA: 'Testing',
    optionB: 'Requirement Analysis',
    optionC: 'Deployment',
    optionD: 'Maintenance',
    correctAnswer: 'B',
  },
  {
    id: 'q_se_004',
    degreeId: 'deg_se_001',
    questionText: 'Which development method uses short iterations?',
    optionA: 'Agile',
    optionB: 'Waterfall',
    optionC: 'Spiral',
    optionD: 'Prototype',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_005',
    degreeId: 'deg_se_001',
    questionText: 'Which tool tracks software project issues?',
    optionA: 'Jira',
    optionB: 'Word',
    optionC: 'Photoshop',
    optionD: 'Excel',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_006',
    degreeId: 'deg_se_001',
    questionText: 'What improves code quality through peer review?',
    optionA: 'Code Review',
    optionB: 'Compilation',
    optionC: 'Deployment',
    optionD: 'Execution',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_007',
    degreeId: 'deg_se_001',
    questionText: 'What does CI/CD help automate?',
    optionA: 'Testing and deployment',
    optionB: 'Graphic design',
    optionC: 'Hardware repair',
    optionD: 'Data entry',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_008',
    degreeId: 'deg_se_001',
    questionText: 'What is unit testing?',
    optionA: 'Testing individual components',
    optionB: 'Testing networks',
    optionC: 'Testing servers',
    optionD: 'Testing users',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_009',
    degreeId: 'deg_se_001',
    questionText: 'DevOps combines development with what?',
    optionA: 'Operations',
    optionB: 'Testing',
    optionC: 'Design',
    optionD: 'Support',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_010',
    degreeId: 'deg_se_001',
    questionText: 'What is refactoring?',
    optionA: 'Improving internal code structure',
    optionB: 'Deleting code',
    optionC: 'Running programs',
    optionD: 'Designing UI',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_011',
    degreeId: 'deg_se_001',
    questionText: 'Which diagram models system structure?',
    optionA: 'UML',
    optionB: 'HTML',
    optionC: 'SQL',
    optionD: 'CSS',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_012',
    degreeId: 'deg_se_001',
    questionText: 'Which practice writes tests before code?',
    optionA: 'TDD',
    optionB: 'Agile',
    optionC: 'Waterfall',
    optionD: 'DevOps',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_013',
    degreeId: 'deg_se_001',
    questionText: 'Which document describes system requirements?',
    optionA: 'SRS',
    optionB: 'API',
    optionC: 'SDK',
    optionD: 'SQL',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_014',
    degreeId: 'deg_se_001',
    questionText: 'Which phase releases software to users?',
    optionA: 'Deployment',
    optionB: 'Testing',
    optionC: 'Design',
    optionD: 'Planning',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_015',
    degreeId: 'deg_se_001',
    questionText: 'Which role ensures product quality?',
    optionA: 'QA Engineer',
    optionB: 'Designer',
    optionC: 'Network Admin',
    optionD: 'Database Admin',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_016',
    degreeId: 'deg_se_001',
    questionText: 'Which system manages source code versions?',
    optionA: 'Git',
    optionB: 'MySQL',
    optionC: 'Linux',
    optionD: 'Docker',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_017',
    degreeId: 'deg_se_001',
    questionText: 'Which method organizes tasks in short meetings?',
    optionA: 'Scrum',
    optionB: 'Waterfall',
    optionC: 'Spiral',
    optionD: 'RAD',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_018',
    degreeId: 'deg_se_001',
    questionText: 'Which concept improves system scalability?',
    optionA: 'Modular design',
    optionB: 'Manual coding',
    optionC: 'Random design',
    optionD: 'Hardcoding',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_019',
    degreeId: 'deg_se_001',
    questionText: 'Which testing verifies system works together?',
    optionA: 'Integration testing',
    optionB: 'Unit testing',
    optionC: 'Manual testing',
    optionD: 'Visual testing',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_020',
    degreeId: 'deg_se_001',
    questionText: 'Which tool builds automation pipelines?',
    optionA: 'Jenkins',
    optionB: 'Figma',
    optionC: 'Excel',
    optionD: 'Canva',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_021',
    degreeId: 'deg_se_001',
    questionText: 'Which concept separates concerns in software?',
    optionA: 'Layered architecture',
    optionB: 'Single file coding',
    optionC: 'Random modules',
    optionD: 'Manual linking',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_022',
    degreeId: 'deg_se_001',
    questionText: 'Which design improves maintainability?',
    optionA: 'Clean code',
    optionB: 'Long functions',
    optionC: 'Complex logic',
    optionD: 'Repeated code',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_023',
    degreeId: 'deg_se_001',
    questionText: 'Which process manages software updates?',
    optionA: 'Maintenance',
    optionB: 'Testing',
    optionC: 'Planning',
    optionD: 'Deployment',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_024',
    degreeId: 'deg_se_001',
    questionText: 'Which platform hosts development repositories?',
    optionA: 'GitHub',
    optionB: 'Instagram',
    optionC: 'Twitter',
    optionD: 'Pinterest',
    correctAnswer: 'A',
  },
  {
    id: 'q_se_025',
    degreeId: 'deg_se_001',
    questionText: 'Which skill is important for developers?',
    optionA: 'Problem solving',
    optionB: 'Painting',
    optionC: 'Cooking',
    optionD: 'Driving',
    correctAnswer: 'A',
  },

  // =========================
  // BUSINESS INFORMATION SYSTEMS (25)
  // =========================
  {
    id: 'q_bis_001',
    degreeId: 'deg_bis_001',
    questionText: 'What does an information system help businesses do?',
    optionA: 'Process and manage data',
    optionB: 'Design graphics',
    optionC: 'Build hardware',
    optionD: 'Control electricity',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_002',
    degreeId: 'deg_bis_001',
    questionText: 'What does ERP stand for?',
    optionA: 'Enterprise Resource Planning',
    optionB: 'Electronic Resource Processing',
    optionC: 'Enterprise Reporting Platform',
    optionD: 'Enterprise Routing Process',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_003',
    degreeId: 'deg_bis_001',
    questionText: 'Which system manages customer relationships?',
    optionA: 'CRM',
    optionB: 'CMS',
    optionC: 'ERP',
    optionD: 'SCM',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_004',
    degreeId: 'deg_bis_001',
    questionText: 'Which department benefits from business systems?',
    optionA: 'All departments',
    optionB: 'Finance only',
    optionC: 'HR only',
    optionD: 'IT only',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_005',
    degreeId: 'deg_bis_001',
    questionText: 'What ensures accuracy of stored data?',
    optionA: 'Data integrity',
    optionB: 'Data speed',
    optionC: 'Data loss',
    optionD: 'Data delay',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_006',
    degreeId: 'deg_bis_001',
    questionText: 'Which tool analyzes business performance?',
    optionA: 'Business intelligence',
    optionB: 'Graphic design',
    optionC: 'Video editing',
    optionD: 'Animation',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_007',
    degreeId: 'deg_bis_001',
    questionText: 'Which concept integrates company processes?',
    optionA: 'ERP',
    optionB: 'Cloud',
    optionC: 'Network',
    optionD: 'Compiler',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_008',
    degreeId: 'deg_bis_001',
    questionText: 'Which system manages supply chains?',
    optionA: 'SCM',
    optionB: 'CRM',
    optionC: 'ERP',
    optionD: 'CMS',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_009',
    degreeId: 'deg_bis_001',
    questionText: 'Which department handles employee information?',
    optionA: 'HR',
    optionB: 'Marketing',
    optionC: 'Finance',
    optionD: 'IT',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_010',
    degreeId: 'deg_bis_001',
    questionText: 'Which technology supports digital transformation?',
    optionA: 'Information systems',
    optionB: 'Printers',
    optionC: 'Hard drives',
    optionD: 'Scanners',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_011',
    degreeId: 'deg_bis_001',
    questionText: 'Which concept helps decision making using data?',
    optionA: 'Decision support system',
    optionB: 'Firewall',
    optionC: 'Compiler',
    optionD: 'Router',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_012',
    degreeId: 'deg_bis_001',
    questionText: 'Which software manages databases?',
    optionA: 'DBMS',
    optionB: 'Photoshop',
    optionC: 'Excel',
    optionD: 'Word',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_013',
    degreeId: 'deg_bis_001',
    questionText: 'Which role manages enterprise systems?',
    optionA: 'Business analyst',
    optionB: 'Graphic designer',
    optionC: 'Driver',
    optionD: 'Architect',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_014',
    degreeId: 'deg_bis_001',
    questionText: 'Which system handles financial records?',
    optionA: 'Accounting system',
    optionB: 'Email server',
    optionC: 'Compiler',
    optionD: 'Router',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_015',
    degreeId: 'deg_bis_001',
    questionText: 'Which concept ensures secure data access?',
    optionA: 'Authentication',
    optionB: 'Compilation',
    optionC: 'Rendering',
    optionD: 'Parsing',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_016',
    degreeId: 'deg_bis_001',
    questionText: 'Which tool helps visualize business data?',
    optionA: 'Dashboard',
    optionB: 'Compiler',
    optionC: 'Router',
    optionD: 'Scanner',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_017',
    degreeId: 'deg_bis_001',
    questionText: 'Which system tracks sales activities?',
    optionA: 'CRM',
    optionB: 'ERP',
    optionC: 'SCM',
    optionD: 'CMS',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_018',
    degreeId: 'deg_bis_001',
    questionText: 'Which role translates business needs into systems?',
    optionA: 'Business analyst',
    optionB: 'Developer',
    optionC: 'Designer',
    optionD: 'Tester',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_019',
    degreeId: 'deg_bis_001',
    questionText: 'Which platform hosts enterprise solutions?',
    optionA: 'SAP',
    optionB: 'Instagram',
    optionC: 'Photoshop',
    optionD: 'Excel',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_020',
    degreeId: 'deg_bis_001',
    questionText: 'Which concept helps automate workflows?',
    optionA: 'Business process automation',
    optionB: 'Manual processing',
    optionC: 'Paper records',
    optionD: 'Phone calls',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_021',
    degreeId: 'deg_bis_001',
    questionText: 'Which system stores organizational knowledge?',
    optionA: 'Knowledge management system',
    optionB: 'Compiler',
    optionC: 'Firewall',
    optionD: 'Router',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_022',
    degreeId: 'deg_bis_001',
    questionText: 'Which department analyzes company performance?',
    optionA: 'Business analytics',
    optionB: 'Design',
    optionC: 'Security',
    optionD: 'Networking',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_023',
    degreeId: 'deg_bis_001',
    questionText: 'Which tool supports project planning?',
    optionA: 'Project management software',
    optionB: 'Compiler',
    optionC: 'Router',
    optionD: 'Printer',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_024',
    degreeId: 'deg_bis_001',
    questionText: 'Which concept links IT with business strategy?',
    optionA: 'Digital transformation',
    optionB: 'Hardware repair',
    optionC: 'Graphic design',
    optionD: 'Gaming',
    correctAnswer: 'A',
  },
  {
    id: 'q_bis_025',
    degreeId: 'deg_bis_001',
    questionText: 'Which skill is important for business analysts?',
    optionA: 'Communication',
    optionB: 'Driving',
    optionC: 'Painting',
    optionD: 'Cooking',
    correctAnswer: 'A',
  },

  // =========================
  // BUSINESS DATA ANALYTICS (25)
  // =========================
  {
    id: 'q_bda_001',
    degreeId: 'deg_bda_001',
    questionText: 'What is the goal of data analytics?',
    optionA: 'Extract insights from data',
    optionB: 'Design hardware',
    optionC: 'Build networks',
    optionD: 'Compile programs',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_002',
    degreeId: 'deg_bda_001',
    questionText: 'Which tool visualizes data dashboards?',
    optionA: 'Power BI',
    optionB: 'Notepad',
    optionC: 'Word',
    optionD: 'Paint',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_003',
    degreeId: 'deg_bda_001',
    questionText: 'What does a dataset represent?',
    optionA: 'Collection of data',
    optionB: 'Computer hardware',
    optionC: 'Network protocol',
    optionD: 'Operating system',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_004',
    degreeId: 'deg_bda_001',
    questionText: 'Which language is widely used for analytics?',
    optionA: 'Python',
    optionB: 'HTML',
    optionC: 'CSS',
    optionD: 'XML',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_005',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept finds patterns in data?',
    optionA: 'Data mining',
    optionB: 'Rendering',
    optionC: 'Compilation',
    optionD: 'Networking',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_006',
    degreeId: 'deg_bda_001',
    questionText: 'Which chart compares categories?',
    optionA: 'Bar chart',
    optionB: 'Pie chart',
    optionC: 'Line chart',
    optionD: 'Histogram',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_007',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept predicts future outcomes?',
    optionA: 'Predictive analytics',
    optionB: 'Graphic design',
    optionC: 'Networking',
    optionD: 'Hardware repair',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_008',
    degreeId: 'deg_bda_001',
    questionText: 'Which tool processes large datasets?',
    optionA: 'Pandas',
    optionB: 'Photoshop',
    optionC: 'Illustrator',
    optionD: 'Canva',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_009',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept measures central tendency?',
    optionA: 'Mean',
    optionB: 'Variance',
    optionC: 'Graph',
    optionD: 'Node',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_010',
    degreeId: 'deg_bda_001',
    questionText: 'Which chart shows trends over time?',
    optionA: 'Line chart',
    optionB: 'Bar chart',
    optionC: 'Pie chart',
    optionD: 'Scatter chart',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_011',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept groups similar data points?',
    optionA: 'Clustering',
    optionB: 'Compilation',
    optionC: 'Rendering',
    optionD: 'Routing',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_012',
    degreeId: 'deg_bda_001',
    questionText: 'Which field combines statistics with computing?',
    optionA: 'Data science',
    optionB: 'Networking',
    optionC: 'Graphics',
    optionD: 'Security',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_013',
    degreeId: 'deg_bda_001',
    questionText: 'Which system stores analytical datasets?',
    optionA: 'Data warehouse',
    optionB: 'Router',
    optionC: 'Compiler',
    optionD: 'Printer',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_014',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept removes inaccurate data?',
    optionA: 'Data cleaning',
    optionB: 'Data duplication',
    optionC: 'Data printing',
    optionD: 'Data editing',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_015',
    degreeId: 'deg_bda_001',
    questionText: 'Which tool creates data visualizations?',
    optionA: 'Tableau',
    optionB: 'Word',
    optionC: 'Excel',
    optionD: 'Paint',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_016',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept identifies relationships between variables?',
    optionA: 'Correlation',
    optionB: 'Compilation',
    optionC: 'Encryption',
    optionD: 'Routing',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_017',
    degreeId: 'deg_bda_001',
    questionText: 'Which chart shows proportions?',
    optionA: 'Pie chart',
    optionB: 'Line chart',
    optionC: 'Histogram',
    optionD: 'Scatter plot',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_018',
    degreeId: 'deg_bda_001',
    questionText: 'Which technology analyzes big datasets quickly?',
    optionA: 'Big Data',
    optionB: 'Networking',
    optionC: 'Graphics',
    optionD: 'Gaming',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_019',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept evaluates model accuracy?',
    optionA: 'Model evaluation',
    optionB: 'Rendering',
    optionC: 'Compilation',
    optionD: 'Routing',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_020',
    degreeId: 'deg_bda_001',
    questionText: 'Which role interprets analytical insights?',
    optionA: 'Data analyst',
    optionB: 'Designer',
    optionC: 'Developer',
    optionD: 'Tester',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_021',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept measures variability in data?',
    optionA: 'Standard deviation',
    optionB: 'Loop',
    optionC: 'Array',
    optionD: 'Graph',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_022',
    degreeId: 'deg_bda_001',
    questionText: 'Which tool builds machine learning models?',
    optionA: 'Scikit-learn',
    optionB: 'Photoshop',
    optionC: 'Illustrator',
    optionD: 'Canva',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_023',
    degreeId: 'deg_bda_001',
    questionText: 'Which concept organizes raw data into useful information?',
    optionA: 'Data processing',
    optionB: 'Data printing',
    optionC: 'Data drawing',
    optionD: 'Data copying',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_024',
    degreeId: 'deg_bda_001',
    questionText: 'Which platform stores large structured datasets?',
    optionA: 'Data warehouse',
    optionB: 'Router',
    optionC: 'Printer',
    optionD: 'Scanner',
    correctAnswer: 'A',
  },
  {
    id: 'q_bda_025',
    degreeId: 'deg_bda_001',
    questionText: 'Which skill is essential for analysts?',
    optionA: 'Critical thinking',
    optionB: 'Driving',
    optionC: 'Cooking',
    optionD: 'Painting',
    correctAnswer: 'A',
  },
];

async function seedQuestionBank() {
  for (const q of questions) {
    await prisma.questionBank.upsert({
      where: { id: q.id },
      update: {},
      create: q,
    });
  }
}

async function main() {
  try {
    await seedQuestionBank();
    console.log('Question bank seed data inserted successfully.');
  } catch (error) {
    console.error('Error seeding question bank:', error);
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
}

main();

